
import { Category, Quote } from './types';

export const FALLBACK_QUOTES: Quote[] = [
  { text: "Aimer, ce n'est pas se regarder l'un l'autre, c'est regarder ensemble dans la même direction.", author: "Antoine de Saint-Exupéry" },
  { text: "Le plus grand bonheur après celui d'aimer, c'est de confesser son amour.", author: "André Gide" },
  { text: "L'amour est un secret entre deux cœurs, un mystère entre deux âmes.", author: "Frédéric Amiel" },
  { text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", author: "Antoine de Saint-Exupéry" },
  { text: "Aimer, c'est savoir dire je t'aime sans parler.", author: "Victor Hugo" },
  { text: "Le cœur a ses raisons que la raison ne connaît point.", author: "Blaise Pascal" },
  { text: "L'amour est la poésie des sens.", author: "Honoré de Balzac" },
  { text: "Il n'y a qu'un bonheur dans la vie, c'est d'aimer et d'être aimé.", author: "George Sand" },
  { text: "La vie est un sommeil, l'amour en est le rêve.", author: "Alfred de Musset" },
  { text: "Aimer, c'est trouver sa richesse hors de soi.", author: "Alain" },
  { text: "L'amour est une fleur délicate, mais il faut avoir le courage d'aller la cueillir.", author: "Stendhal" },
  { text: "Le premier soupir de l'amour est le dernier de la sagesse.", author: "Antoine Bret" },
  { text: "L'amour est l'emblème de l'éternité ; il confond toute notion de temps.", author: "Madame de Staël" },
  { text: "Il n'est rien de réel que le rêve et l'amour.", author: "Anna de Noailles" },
  { text: "L'amour, c'est quand l'autre devient plus important que soi.", author: "Anonyme" },
  { text: "Une vie sans amour, c'est comme un jardin sans soleil.", author: "Oscar Wilde" },
  { text: "Le couple est une conversation qui ne finit jamais.", author: "Anonyme" },
  { text: "Aimer, c'est être vulnérable et fort en même temps.", author: "Anonyme" },
  { text: "L'amour ne se prédit pas, il se construit.", author: "Anonyme" },
  { text: "Deux âmes qui se rencontrent, c'est comme deux étoiles qui s'alignent.", author: "Anonyme" },
  { text: "L'amour est la seule chose qui se double à chaque fois qu'on la partage.", author: "Albert Schweitzer" },
  { text: "S'aimer, c'est donner à l'autre le pouvoir de vous détruire, mais lui faire confiance.", author: "Anonyme" },
  { text: "Le véritable amour n'a pas d'âge, pas de limites, pas de mort.", author: "John Galsworthy" },
  { text: "L'amour est une amitié qui a pris feu.", author: "Jeremy Taylor" },
  { text: "On n'aime pas quelqu'un pour ses qualités, on l'aime malgré ses défauts.", author: "Anonyme" },
  { text: "La mesure de l'amour, c'est d'aimer sans mesure.", author: "Saint Augustin" },
  { text: "Le bonheur n'est réel que lorsqu'il est partagé.", author: "Christopher McCandless" },
  { text: "L'amour est un voyage sans fin où le paysage est toujours nouveau.", author: "Anonyme" },
  { text: "Être aimé, c'est plus qu'être riche, car c'est être heureux.", author: "Claude Tillier" },
  { text: "L'amour est le soleil de l'âme.", author: "Victor Hugo" }
];

export const FALLBACK_QUESTIONS: Record<Category, string[]> = {
  [Category.DEEP]: [
    "Quelle est la chose que tu essaies encore de comprendre sur toi-même ?",
    "Si tu pouvais changer une chose dans la façon dont tu as été élevé(e), ce serait quoi ?",
    "Que signifie le mot 'foyer' pour toi ?",
    "Quelle est ta plus grande peur concernant notre relation ?",
    "Quand t'es-tu senti(e) vraiment vu(e) et compris(e) par moi pour la dernière fois ?",
    "Quelle est la leçon la plus difficile que la vie t'ait apprise jusqu'ici ?",
    "Quel aspect de ta personnalité aimerais-tu que je comprenne mieux ?",
    "Si tu pouvais voir une scène de ton futur, laquelle choisirais-tu ?",
    "Quelle est ta définition d'une 'vie réussie' ?",
    "Y a-t-il quelque chose que tu n'as jamais osé me dire par peur de ma réaction ?",
    "Quel est le plus grand sacrifice que tu aies fait par amour ?",
    "Quelle partie de ton passé a le plus influencé qui tu es aujourd'hui ?",
    "Qu'est-ce qui te rend le plus prix de nous ?",
    "Si notre relation était un livre, quel en serait le titre actuel ?",
    "Quel est le trait de caractère que tu admires le plus chez tes parents ?",
    "Comment ta vision de l'amour a-t-elle évolué depuis que nous sommes ensemble ?",
    "Quel est le souvenir d'enfance qui te réconforte le plus ?",
    "Si tu devais me confier une mission pour te rendre plus heureux/se, quelle serait-elle ?",
    "Quelle est la différence entre 'aimer' et 'être amoureux' selon toi ?",
    "Quel est ton plus grand regret et comment t'a-t-il changé ?",
    "Quelle est la valeur non négociable pour toi dans une amitié ?",
    "As-tu déjà ressenti une connexion spirituelle avec quelqu'un ou quelque chose ?",
    "Si tu mourais demain, quel serait ton plus grand regret inachevé ?",
    "Quel est le masque que tu portes le plus souvent en société ?",
    "Comment gères-tu la solitude et que t'apprend-elle ?",
    "Quelle est la critique que l'on te fait souvent et qui te blesse le plus ?",
    "Si tu pouvais demander pardon à une personne de ton passé, qui serait-ce ?",
    "Qu'est-ce qui te donne le sentiment d'être vraiment vivant(e) ?",
    "Penses-tu que les gens peuvent réellement changer en profondeur ?",
    "Quelle est la part de toi que tu as le plus de mal à accepter ?",
    "Quel est le compliment le plus profond qu'on puisse te faire ?",
    "Quelle est ta philosophie personnelle en une seule phrase ?",
    "Comment aimerais-tu que l'on se souvienne de toi ?",
    "Quelle est la différence entre la justice et la vengeance selon toi ?",
    "Quel est le vide que tu essaies de combler dans ta vie actuelle ?",
    "Crois-tu au destin ou au pur hasard ?",
    "Quel est le moment où tu t'es senti(e) le plus courageux/se ?",
    "Qu'est-ce qui est plus important : être aimé ou être compris ?",
    "Si tu pouvais revivre une seule journée de ta vie, laquelle serait-ce ?",
    "Quelle est la vérité que tu as mis le plus de temps à admettre ?",
    // NOUVELLES QUESTIONS DEEP
    "Quel est le fardeau émotionnel que tu portes et que tu aimerais déposer ?",
    "À quoi ressemble ton 'lieu sûr' mental quand ça ne va pas ?",
    "Si tu pouvais avoir une réponse absolue à une question existentielle, laquelle poserais-tu ?",
    "Quelle est la plus grande idée fausse que les gens ont sur toi ?",
    "Qu'est-ce qui te fait pleurer, mais que tu gardes souvent pour toi ?",
    "Si tu pouvais écrire une lettre à ton toi de 15 ans, que lui dirais-tu ?",
    "Quelle est la qualité que tu as perdue en grandissant et que tu aimerais retrouver ?",
    "Dans quels moments te sens-tu le plus en paix avec toi-même ?",
    "Qu'est-ce que tu ne pardonnerais jamais, même par amour ?",
    "Quelle est ta relation avec ton propre corps aujourd'hui ?",
    "Si tu devais choisir une émotion à ne plus jamais ressentir, laquelle serait-ce ?",
    "Quelle est la chose la plus gentille que tu aies faite pour un inconnu ?",
    "As-tu l'impression de vivre la vie que tu as choisie ou celle qu'on attend de toi ?",
    "Quelle est ta plus grande insécurité physique et pourquoi ?",
    "Si tu pouvais effacer un souvenir douloureux, le ferais-tu, sachant que cela changerait qui tu es ?",
    "Qu'est-ce qui te révolte le plus dans le monde actuel ?",
    "Quelle est la décision la plus difficile que tu aies jamais eu à prendre ?",
    "Si tu savais que tu allais perdre la mémoire, quel souvenir voudrais-tu garder en dernier ?",
    "Quelle est la personne qui t'a le plus déçu et as-tu réussi à tourner la page ?",
    "Qu'est-ce qui te motive à te lever le matin quand tout va mal ?",
    "Penses-tu mériter le bonheur ? Pourquoi ?",
    "Quelle est la plus grande preuve de maturité selon toi ?",
    "Qu'est-ce qui te fait le plus peur dans le fait de vieillir ?",
    "Si tu pouvais changer un trait de caractère chez moi pour mon bien, lequel serait-ce ?",
    "Quelle est la limite entre la vie privée et le secret dans un couple ?",
    "Te sens-tu libre ?",
    "Quelle est l'habitude toxique dont tu as le plus de mal à te défaire ?",
    "Si tu devais mourir pour une cause, laquelle vaudrait ce sacrifice ?",
    "Quel est le moment où tu as été le plus fier de toi ?",
    "Crois-tu en l'âme sœur ou penses-tu que l'amour est un choix ?",
    "Quelle est la chose que tu aimerais que je fasse plus souvent pour te soutenir ?",
    "As-tu peur de ressembler à tes parents ?",
    "Si tu pouvais voir le monde à travers mes yeux pendant une heure, que penses-tu que tu verrais ?",
    "Quelle est la chose la plus importante que tu aies apprise sur le pardon ?",
    "Si tu devais décrire ton âme avec une météo, quel temps ferait-il aujourd'hui ?",
    "Qu'est-ce qui te manque le plus de ta vie de célibataire (si quelque chose te manque) ?",
    "Quelle est la plus grande faiblesse de notre couple selon toi ?",
    "Et quelle est sa plus grande force indestructible ?",
    "Si tu pouvais revivre une conversation que nous avons eue pour changer ce que tu as dit, laquelle serait-ce ?",
    "Qu'est-ce qui te fait sentir petit face à l'univers ?",
    "Quelle est la chose matérielle à laquelle tu tiens le plus et pourquoi ?",
    "Si tu pouvais connaître la date de ta mort, voudrais-tu la savoir ?",
    "Qu'est-ce que tu aimerais oser faire mais que la peur t'empêche de réaliser ?",
    "Quelle est la valeur morale que tu transgresserais pour sauver un proche ?",
    "Te considères-tu comme une bonne personne ?",
    "Qu'est-ce que l'argent ne pourra jamais acheter pour toi ?",
    "Si tu devais passer une année seul(e) sur une île, qu'apprendrais-tu sur toi ?",
    "Quelle est la chanson qui te bouleverse à chaque écoute ?",
    "Penses-tu que tout arrive pour une raison ?",
    "Si tu pouvais guérir une blessure de mon passé, laquelle choisirais-tu ?"
  ],
  [Category.FUNNY]: [
    "Quelle est la chose la plus embarrassante qui t'est arrivée lors d'un rendez-vous ?",
    "Si nous étions dans un film d'horreur, qui mourrait en premier ?",
    "Quel est ton talent le plus inutile ?",
    "Si tu devais être un appareil de cuisine, lequel serais-tu et pourquoi ?",
    "Quelle est la combinaison alimentaire la plus bizarre que tu apprécies vraiment ?",
    "Si tu pouvais échanger ta vie avec un personnage de dessin animé pendant une journée, qui serait-ce ?",
    "Quelle est la loi la plus absurde que tu inventerais si tu étais dictateur ?",
    "Si les animaux pouvaient parler, lequel serait le plus impoli ?",
    "Quelle est la pire coiffure que tu aies jamais eue ?",
    "Quelle chanson est ton plaisir coupable sous la douche ?",
    "Si tu étais un parfum de glace, lequel décrirait le mieux ton humeur actuelle ?",
    "Quel est le truc le plus bizarre que tu aies acheté sur un coup de tête ?",
    "Si on devait survivre à une apocalypse zombie, quel serait ton rôle ?",
    "Quelle célébrité serait ton 'free pass' et pourquoi c'est drôle ?",
    "Quelle est la pire excuse que tu aies utilisée pour annuler un plan ?",
    "Si tu étais une mouche, dans quelle pièce aimerais-tu espionner ?",
    "Quel est le mot que tu trouves le plus ridicule à prononcer ?",
    "Si tu pouvais avoir un orchestre qui joue une musique de fond pour chaque moment de ta vie, quel genre choisirais-tu ?",
    "Quelle est ta danse de la victoire la plus ridicule ?",
    "Si on devait se déguiser en duo célèbre, qui choisirais-tu ?",
    "Quel est l'objet le plus inutile que tu possèdes mais que tu refuses de jeter ?",
    "Quelle est la théorie de complot la plus débile à laquelle tu pourrais croire ?",
    "Si tu étais un fantôme, qui choisirais-tu de hanter juste pour l'embêter ?",
    "Quel est ton 'super-pouvoir' de paresseux ?",
    "Si tu devais participer à une émission de télé-réalité, laquelle choisirais-tu ?",
    "Quelle est la chose la plus stupide que tu as faite par défi ?",
    "Si tu pouvais remplacer le rire des gens par un bruit d'animal, lequel choisirais-tu ?",
    "Quel est le nom de super-héros le plus naze que tu pourrais avoir ?",
    "Quelle est la chose la plus bizarre que tu faisais quand tu étais enfant ?",
    "Si tu étais un meuble IKEA, quel nom imprononçable porterais-tu ?",
    "Quel est le crime le plus drôle que tu pourrais commettre par accident ?",
    "Si tu devais te battre contre 100 canards de la taille d'un cheval, comment t'y prendrais-tu ?",
    "Quelle est la pub que tu détestes le plus au monde ?",
    "Si tu pouvais interdire un mot pour toujours, lequel serait-ce ?",
    "Quelle est ta pire imitation et peux-tu la faire maintenant ?",
    "Si tu étais une saveur de chips, laquelle serais-tu ?",
    "Quel est le truc le plus étrange que tu as cherché sur Google récemment ?",
    "Si tu devais vivre dans un centre commercial pour toujours, lequel choisirais-tu ?",
    "Quelle est la rumeur la plus folle que tu aies entendue sur toi ?",
    "Si tu étais un Pokémon, quel serait ton type et ton attaque spéciale ?",
    // NOUVELLES QUESTIONS FUNNY
    "Si tu devais manger un seul aliment de la même couleur pour le reste de ta vie, quelle couleur choisirais-tu ?",
    "Quelle est l'insulte la plus créative que tu puisses inventer sans dire de gros mots ?",
    "Si tes mains étaient remplacées par des objets, lesquels seraient les plus gênants ?",
    "Quel est le pire cadeau que tu aies jamais reçu et pour lequel tu as dû faire semblant d'être content ?",
    "Si tu pouvais rendre un bruit corporel totalement silencieux, lequel choisirais-tu ?",
    "Quelle est la chose la plus bizarre que tu aies vue quelqu'un faire dans sa voiture ?",
    "Si tu étais un serial killer, quelle serait ta signature ridicule ?",
    "Quel animal serait le plus effrayant s'il avait la taille d'une baleine ?",
    "Si tu devais porter un panneau autour du cou avertissant les gens d'un de tes défauts, que dirait-il ?",
    "Quelle est ta pire histoire de toilettes (si tu oses la raconter) ?",
    "Si tu pouvais fusionner deux sports pour en créer un nouveau, lesquels choisirais-tu ?",
    "Quel est le mème qui te fait rire à tous les coups ?",
    "Si tu étais un dictateur bienveillant, quel hymne national choisirais-tu ?",
    "Quelle est la chose la plus stupide pour laquelle tu as pleuré ?",
    "Si tu devais choisir une mascotte pour te représenter, ce serait quoi ?",
    "Quelle est la pire 'pickup line' (phrase de drague) que tu connaisses ?",
    "Si tu pouvais avoir un bouton 'Mute' pour une personne dans ta vie, qui serait-ce ?",
    "Quel est le vêtement le plus laid que tu as porté en pensant être stylé ?",
    "Si tu devais te battre en duel avec une célébrité, qui choisirais-tu pour être sûr de gagner ?",
    "Quelle est la chose la plus bizarre que tu aies mangée par politesse ?",
    "Si tu pouvais changer le son de ta voix pour celle d'un personnage célèbre, qui choisirais-tu ?",
    "Quel est le pire endroit pour avoir une crise de hoquet ?",
    "Si tu devais être un objet du quotidien, lequel verrait les choses les plus traumatisantes ?",
    "Quelle est ta technique secrète pour faire semblant d'écouter ?",
    "Si tu pouvais voler quelque chose sans conséquence, mais que ce doit être quelque chose de moins de 5€, que volerais-tu ?",
    "Quel est le film que tu as vu le plus de fois et dont tu as honte ?",
    "Si tu étais un virus informatique, quel message afficherais-tu sur les écrans ?",
    "Quelle est la chose la plus absurde que tu aies faite par amour ?",
    "Si tu devais inventer un nouveau jour de la semaine, comment s'appellerait-il et on ferait quoi ?",
    "Quel est le bruit le plus agaçant au monde selon toi ?",
    "Si tu pouvais rétrécir n'importe quel animal pour le mettre dans ta poche, lequel choisirais-tu ?",
    "Quelle est la pire chose à dire lors d'un premier rendez-vous ?",
    "Si tu étais un panneau de signalisation, que dirais-tu ?",
    "Quelle est la blague de papa la plus nulle que tu connaisses ?",
    "Si tu devais te faire tatouer le visage de quelqu'un sur les fesses, qui serait-ce ?",
    "Quel est le pire conseil que tu aies donné à quelqu'un ?",
    "Si tu pouvais contrôler les rêves de quelqu'un d'autre, que lui ferais-tu rêver ?",
    "Quelle est la phobie la plus ridicule que tu aies (ou aies eue) ?",
    "Si tu devais être allergique à quelque chose d'essentiel, ce serait quoi ?",
    "Quel est le surnom le plus ridicule qu'on t'ait donné ?",
    "Si tu pouvais créer une secte, quel serait le principe de base ?",
    "Quelle est la chose la plus sale que tu aies touchée ?",
    "Si tu devais vivre dans un jeu vidéo des années 90, lequel choisirais-tu ?",
    "Quel est le pire ingrédient à mettre sur une pizza ?",
    "Si tu pouvais parler couramment le 'chien', que dirais-tu au premier chien que tu croises ?",
    "Quelle est la situation la plus gênante où tu as pété ?",
    "Si tu devais n'avoir qu'une seule expression faciale pour toujours, laquelle choisirais-tu ?",
    "Quel est le pire endroit pour faire une demande en mariage ?",
    "Si tu pouvais transformer l'eau du robinet en une autre boisson, laquelle serait-ce ?",
    "Quelle est la chose la plus bizarre que tu aies trouvée par terre ?"
  ],
  [Category.ROMANTIC]: [
    "Quel a été le moment exact où tu as réalisé que tu avais des sentiments pour moi ?",
    "Quel est ton trait physique préféré chez moi ?",
    "Si nous pouvions tout lâcher et partir en escapade romantique maintenant, où irions-nous ?",
    "Quelle est la petite chose que je fais qui te fait te sentir incroyablement aimé(e) ?",
    "Décris notre premier baiser en utilisant seulement trois adjectifs.",
    "Quelle chanson te fait instantanément penser à nous ?",
    "Quel est le plus beau compliment que je t'ai jamais fait ?",
    "Si on devait recréer notre premier rendez-vous, que changerais-tu ?",
    "Quel est ton langage de l'amour dominant ?",
    "Qu'est-ce qui t'a attiré chez moi en premier ?",
    "Si tu devais écrire un poème de deux lignes sur nous, que dirais-tu ?",
    "Quelle est ta partie préférée de notre routine quotidienne ?",
    "Quel geste romantique cliché trouves-tu secrètement adorable ?",
    "Où est l'endroit le plus romantique où nous soyons allés ensemble ?",
    "Quelle odeur te rappelle le plus ma présence ?",
    "Comment décrirais-tu l'alchimie entre nous à un étranger ?",
    "Quel est le rêve le plus romantique que tu aies fait de nous ?",
    "Si tu devais me donner un nouveau surnom aujourd'hui, lequel serait-ce ?",
    "Quelle est la chose que tu préfères faire avec moi le dimanche matin ?",
    "Qu'est-ce qui te manque le plus chez moi quand on est séparés ?",
    "Quel vêtement me va le mieux selon toi ?",
    "Si on devait danser sur une seule chanson pour le reste de notre vie, laquelle ?",
    "Quel est le plus petit détail que tu as remarqué chez moi aujourd'hui ?",
    "Comment décrirais-tu mon regard quand je suis amoureux/se ?",
    "Quel est le souvenir de nous qui te fait sourire dès que tu y penses ?",
    "Si notre amour était une couleur, quelle nuance de rouge serait-ce ?",
    "Quelle est la chose la plus audacieuse que tu aimerais essayer avec moi ?",
    "Si tu pouvais m'offrir n'importe quel cadeau immatériel, que choisirais-tu ?",
    "Quel est l'endroit sur mon corps où tu préfères poser ta main ?",
    "Quelle est la première chose que tu as pensé quand tu as vu mon profil ou mon visage ?",
    "Si on devait s'écrire des lettres d'amour à l'ancienne, qui craquerait en premier ?",
    "Quel est le secret de notre complicité selon toi ?",
    "Si je devais être une fleur dans ton jardin, laquelle serais-tu ?",
    "Quel est le moment où tu te sens le plus en sécurité avec moi ?",
    "Comment aimerais-tu être embrassé(e) là maintenant ?",
    "Quelle est la promesse que tu veux me faire aujourd'hui ?",
    "Si notre vie était une playlist, quelle serait la chanson d'ouverture ?",
    "Quelle est la chose que tu trouves la plus sexy chez moi (mentalement) ?",
    "Quel est le voyage de noces (réel ou imaginaire) dont tu rêves ?",
    "Pourquoi moi, et pas quelqu'un d'autre ?",
    // NOUVELLES QUESTIONS ROMANTIC
    "Quel est le baiser de film que tu aimerais qu'on recrée ?",
    "Si tu devais dessiner mon âme, à quoi ressemblerait-elle ?",
    "Quelle est la partie de ton corps que tu aimes que je touche le plus ?",
    "Quel est le moment le plus vulnérable que nous avons partagé ?",
    "Si tu pouvais arrêter le temps lors d'un moment précis de notre passé, lequel choisirais-tu ?",
    "Quelle est la qualité chez moi qui t'inspire le plus ?",
    "Si tu devais me décrire à un aveugle, que dirais-tu ?",
    "Quel est le 'je t'aime' silencieux que je te dis souvent sans que je m'en rende compte ?",
    "Quelle est la tenue dans laquelle tu me trouves irrésistible ?",
    "Si nous étions seuls au monde, que ferions-nous de nos journées ?",
    "Quel est le goût de mes lèvres selon toi ?",
    "Quand est-ce que tu me trouves le plus beau/belle : au réveil ou apprêté(e) ?",
    "Si tu pouvais revivre notre première nuit, changerais-tu quelque chose ?",
    "Quelle est la plus belle surprise que je t'aie faite ?",
    "Quel est le scénario romantique dont tu rêves secrètement ?",
    "Comment sais-tu que je vais mal sans que je dise un mot ?",
    "Quelle est la chose la plus gentille que tu aies dite à tes amis à mon propos ?",
    "Si tu devais m'embrasser sous la pluie ou sous la neige, que choisirais-tu ?",
    "Quelle est l'habitude que j'ai qui te fait fondre ?",
    "Si notre amour était une saison, laquelle serait-ce ?",
    "Quel est le compliment que tu aimerais que je te fasse plus souvent ?",
    "Si tu pouvais lire dans mes pensées pendant un câlin, qu'aimerais-tu entendre ?",
    "Quelle est la différence entre nous qui nous rend complémentaires ?",
    "Si tu devais choisir une photo de nous pour mettre dans un médaillon, laquelle serait-ce ?",
    "Quel est le repas le plus romantique que nous ayons partagé ?",
    "Quelle est la caresse qui te donne instantanément des frissons ?",
    "Si je devais partir demain, quel message me laisserais-tu ?",
    "Quelle est la chose la plus folle que tu serais prêt(e) à faire par amour pour moi ?",
    "Comment définis-tu l'intimité au-delà du sexe ?",
    "Quel est le moment où tu as été le plus fier d'être mon/ma partenaire ?",
    "Si tu pouvais m'emmener n'importe où pour un dîner aux chandelles ce soir ?",
    "Quelle est la chose que je fais au lit qui te plaît le plus ?",
    "Si tu devais écrire un vœu de mariage aujourd'hui, que dirait-il ?",
    "Quel est le regard que je te lance que tu préfères ?",
    "Si nous devions avoir une 'chanson de couple' différente, laquelle proposerais-tu ?",
    "Quel est le plus grand obstacle que notre amour a surmonté ?",
    "Si tu pouvais passer une journée entière au lit avec moi, que ferions-nous (à part dormir) ?",
    "Quelle est la saveur de notre relation : sucrée, épicée, salée ?",
    "Quel est le moment où tu as eu peur de me perdre ?",
    "Si tu devais me dédier un livre, quel en serait le sujet ?",
    "Quelle est la petite attention quotidienne qui te manque si je ne la fais pas ?",
    "Comment imagines-tu notre dernier baiser ?",
    "Si tu pouvais capturer mon rire dans une boîte, quand l'ouvrirais-tu ?",
    "Quelle est la partie de mon visage que tu pourrais regarder pendant des heures ?",
    "Si tu devais choisir un mot pour définir notre connexion sexuelle ?",
    "Quel est le souvenir sensuel le plus vif que tu gardes de nous ?",
    "Si tu pouvais m'offrir une étoile, comment la nommerais-tu ?",
    "Qu'est-ce qui fait de moi ton meilleur ami et ton amant en même temps ?",
    "Si tu devais me re-séduire aujourd'hui, comment t'y prendrais-tu ?",
    "Quelle est la certitude que tu as sur nous deux ?"
  ],
  [Category.FUTURE]: [
    "Où nous vois-tu vivre dans 10 ans ?",
    "Quel est le rêve que tu n'as jamais dit à personne ?",
    "Si l'argent n'était pas un problème, à quoi ressemblerait notre vie ?",
    "Quel héritage veux-tu laisser derrière toi ?",
    "Quelle est l'aventure que tu veux vivre avec moi avant nos 50 ans ?",
    "Combien d'enfants ou d'animaux vois-tu dans notre futur ?",
    "Quelle est la première chose que nous devrions acheter si nous gagnions au loto ?",
    "Quelle compétence aimerais-tu que nous apprenions ensemble ?",
    "À quoi ressemblerait notre maison idéale ?",
    "Comment imagines-tu notre vie à la retraite ?",
    "Quelle destination de voyage est tout en haut de ta liste ?",
    "Si on devait déménager dans un autre pays, lequel choisirais-tu ?",
    "Quel projet créatif aimerais-tu que nous lancions à deux ?",
    "Quelle tradition veux-tu instaurer pour nos anniversaires ?",
    "Comment penses-tu que nous allons évoluer dans les 5 prochaines années ?",
    "Quel est l'objectif personnel que tu aimerais que je t'aide à atteindre ?",
    "Si on devait écrire un livre ensemble, de quoi parlerait-il ?",
    "Quel est le plus grand défi que nous surmonterons ensemble ?",
    "Si tu pouvais automatiser une tâche ménagère pour toujours, laquelle ?",
    "Quelle est la chose la plus folle que tu aimerais faire une fois ?",
    "Quelle serait la première étape de notre plan de conquête du monde ?",
    "Quel genre de parents (ou propriétaires d'animaux) serons-nous ?",
    "Dans quelle ville aimerais-tu que nous passions un an en immersion ?",
    "Quel est le festival ou l'événement mondial que nous devons voir ensemble ?",
    "Si on ouvrait un restaurant, quel serait le concept et le nom ?",
    "Quelle est la voiture de tes rêves pour nos futurs road trips ?",
    "Comment décrirais-tu notre 'vieux nous' ?",
    "Quelle est la peur du futur que tu aimerais que nous affrontions ensemble ?",
    "Quelle est la chose que tu refuses de changer, même dans 20 ans ?",
    "Si on devait créer une fondation caritative, quelle cause soutiendrait-on ?",
    "Quel est le talent caché que tu penses développer plus tard ?",
    "À quoi ressemblera notre premier grand investissement commun ?",
    "Quelle est la langue que nous devrions apprendre ensemble ?",
    "Comment fêterons-nous nos 25 ans de rencontre ?",
    "Si tu pouvais concevoir ton propre robot domestique, que ferait-il ?",
    "Quel est l'objet de notre présent que nous garderons toute notre vie ?",
    "Dans quel domaine serons-nous les plus complices plus tard ?",
    "Si on devait vivre sur une autre planète, serais-tu partant(e) ?",
    "Quel est le rêve d'enfant que tu veux encore réaliser ?",
    "Quelle est la plus belle promesse que l'on puisse se faire pour l'avenir ?",
    // NOUVELLES QUESTIONS FUTURE
    "Si on pouvait vivre éternellement, accepterais-tu ou refuserais-tu ?",
    "Quelle technologie du futur espères-tu voir de ton vivant ?",
    "Si nous devions construire notre propre maison de A à Z, qui ferait quoi ?",
    "Quel genre de grands-parents serons-nous ?",
    "Si tu pouvais connaître un seul événement mondial futur, lequel voudrais-tu savoir ?",
    "Quelle est la tradition de Noël (ou autre fête) que tu veux absolument créer ?",
    "Si nous avions une heure de gloire mondiale, ce serait pour quelle raison ?",
    "Quel est le hobby que tu nous vois pratiquer à 70 ans sur notre porche ?",
    "Si tu pouvais choisir l'époque de notre retraite (passé ou futur), laquelle choisirais-tu ?",
    "Quelle est la chose que tu veux absolument avoir accomplie avant de mourir ?",
    "Si nous devions vivre sur un bateau pendant un an, où irions-nous ?",
    "Quel est le luxe que tu espères qu'on pourra se payer un jour ?",
    "Si tu pouvais changer de carrière demain sans risque, que ferais-tu ?",
    "Comment imagines-tu notre routine du matin dans 15 ans ?",
    "Quelle est la chose que tu espères que nos enfants (ou neveux) apprendront de nous ?",
    "Si nous devions laisser une capsule temporelle à ouvrir dans 50 ans, qu'y mettrais-tu ?",
    "Quel est le pays où tu ne voudrais jamais vivre ?",
    "Si tu pouvais garantir une chose pour notre avenir, la santé ou la richesse, que choisirais-tu ?",
    "Quelle est la cause pour laquelle tu voudrais te battre dans le futur ?",
    "Si on devait tout recommencer à zéro dans une ville inconnue, quel serait notre premier réflexe ?",
    "Quel est le film que tu as hâte de montrer à notre future famille ?",
    "Si tu pouvais investir dans une entreprise aujourd'hui, laquelle serait-ce ?",
    "À quel âge penses-tu que nous serons au sommet de notre bonheur ?",
    "Si nous devions écrire nos mémoires, quel serait le titre du chapitre actuel ?",
    "Quelle est la chose que tu veux améliorer chez toi avant l'année prochaine ?",
    "Si on pouvait téléporter notre maison n'importe où, où la poserais-tu ?",
    "Quel est le défi physique (marathon, montagne...) que tu voudrais qu'on relève ?",
    "Si tu pouvais choisir les prénoms de nos futurs animaux de compagnie maintenant, ce serait quoi ?",
    "Quelle est la chose que tu ne veux absolument pas regretter sur ton lit de mort ?",
    "Comment veux-tu qu'on célèbre nos 50 ans de mariage ?",
    "Si tu pouvais effacer une invention du futur pour sauver l'humanité, laquelle ?",
    "Quel est le savoir-faire manuel que tu veux maîtriser plus tard ?",
    "Si nous devions devenir fermiers, qu'élèverions-nous ?",
    "Quelle est la chose que tu espères que la science guérira bientôt ?",
    "Si on gagnait un voyage dans l'espace, irais-tu ?",
    "Quel est le petit commerce (café, librairie...) que tu nous verrais tenir ?",
    "Si tu pouvais prédire une chose sur notre couple, ce serait quoi ?",
    "Quelle est la valeur que tu veux transmettre aux générations futures ?",
    "Si on devait vivre sans internet pendant un mois chaque année, où irait-on ?",
    "Quel est le meuble de famille que tu veux absolument récupérer ?",
    "Si tu pouvais choisir notre voisin idéal, qui serait-ce ?",
    "Quelle est la catastrophe naturelle qui te fait le plus peur pour l'avenir ?",
    "Si on devait adopter un mode de vie alternatif (vanlife, tiny house...), lequel te tente ?",
    "Quel est le livre que tu veux avoir lu avant la fin de l'année ?",
    "Si tu pouvais choisir notre dernière demeure, où serait-elle ?",
    "Quelle est l'habitude écologique que tu veux qu'on adopte ?",
    "Si tu pouvais être le mentor de quelqu'un, que lui apprendrais-tu ?",
    "Quelle est la photo de nous que tu veux voir encadrée dans notre futur salon ?",
    "Si on devait faire le tour du monde, on commencerait par l'Est ou l'Ouest ?",
    "Quel est le mot qui définira notre avenir ?"
  ],
  [Category.RANDOM]: [
    "Si tu étais un fantôme, qui hanterais-tu en premier ?",
    "Préférerais-tu toujours chanter ou toujours danser ?",
    "Quelle est la théorie du complot que tu penses être vraie ?",
    "Si tu pouvais avoir n'importe quel animal comme compagnon ?",
    "Sur quel sujet pourrais-tu faire une présentation sans préparation ?",
    "Si tu étais une couleur, laquelle serais-tu aujourd'hui ?",
    "Quel est l'objet le plus étrange dans ton sac en ce moment ?",
    "Si tu pouvais remonter le temps, à quelle époque ?",
    "Préférerais-tu l'espace ou le fond de l'océan ?",
    "Quelle est ta citation de film préférée ?",
    "Si tu gagnais une médaille d'or, pour quelle épreuve ?",
    "Quel est le premier site web que tu consultes ?",
    "Si tu pouvais parler une autre langue instantanément ?",
    "Quel est l'aliment que tout le monde aime mais que tu détestes ?",
    "Si tu étais un super-héros, quel serait ton nom ?",
    "Quel est le fait historique le plus fascinant ?",
    "Comment appellerais-tu le mois d'Avril ?",
    "Quelle est la technologie du futur que tu attends ?",
    "Si tu pouvais cloner un objet de ta maison ?",
    "Quel est le dernier rêve étrange dont tu te souviennes ?",
    "Si tu devais vivre dans un ascenseur pendant 24h avec une célébrité ?",
    "Quel est le légume le plus sous-estimé selon toi ?",
    "Si tu pouvais fusionner deux animaux pour créer une nouvelle espèce ?",
    "Quelle est la première chose que tu ferais si tu étais invisible ?",
    "Quel est le bruit que tu préfères au monde ?",
    "Si tu devais manger un seul plat jusqu'à la fin de tes jours ?",
    "Quel est le livre qui a changé ta façon de voir le monde ?",
    "Si tu pouvais changer ton prénom, lequel choisirais-tu ?",
    "Quel est le talent que tu as toujours voulu avoir sans jamais essayer ?",
    "Si tu étais coincé dans un jeu vidéo, lequel serait-ce ?",
    "Quel est le pire conseil qu'on t'ait jamais donné ?",
    "Si tu pouvais posséder un objet historique célèbre ?",
    "Quel est ton type de météo préféré pour rester au lit ?",
    "Si tu pouvais être un expert mondial dans un domaine inutile ?",
    "Quel est le sport le plus bizarre que tu aies vu à la télé ?",
    "Si tu étais une police d'écriture, laquelle serais-tu ?",
    "Quel est le secret que tu n'as jamais dit car il est trop banal ?",
    "Si tu devais donner un cours à l'université, quel serait le sujet ?",
    "Quelle est la chose la plus courageuse que tu aies faite seule ?",
    "Si tu pouvais être une intelligence artificielle, quel serait ton but ?",
    // NOUVELLES QUESTIONS RANDOM
    "Si tu étais une sauce, laquelle serais-tu ?",
    "Plutôt avoir des bras en spaghetti ou des jambes en guimauve ?",
    "Si tu pouvais dîner avec un personnage de fiction, qui choisirais-tu ?",
    "Quel est le mot le plus drôle de la langue française selon toi ?",
    "Si tu devais vivre dans une époque sans électricité, quel métier ferais-tu ?",
    "Plutôt ne plus jamais avoir besoin de dormir ou ne plus jamais avoir besoin de manger ?",
    "Si tu étais un panneau de danger, que représenterais-tu ?",
    "Quelle est la chanson que tu choisirais pour ton entrée sur un ring de boxe ?",
    "Si tu pouvais communiquer avec un type d'objet, lequel choisirais-tu ?",
    "Plutôt avoir des doigts à la place des orteils ou des orteils à la place des doigts ?",
    "Si tu étais un dieu de la mythologie, tu serais le dieu de quoi ?",
    "Quel est le débat le plus inutile sur lequel tu as une opinion tranchée ?",
    "Si tu pouvais te réincarner en plante, laquelle choisirais-tu ?",
    "Plutôt savoir comment tu vas mourir ou quand tu vas mourir ?",
    "Si ta vie était un genre de film, ce serait quoi (comédie, drame, sci-fi) ?",
    "Quelle est la chose la plus étrange que tu aies vue dans le métro ?",
    "Si tu pouvais faire pleuvoir de la nourriture, laquelle choisirais-tu ?",
    "Plutôt être toujours en retard de 10 min ou toujours en avance de 20 min ?",
    "Si tu devais porter une seule couleur pour le reste de ta vie ?",
    "Quel est l'animal mythologique que tu voudrais voir exister ?",
    "Si tu pouvais effacer un jour de la semaine, lequel serait-ce ?",
    "Plutôt avoir une voix de robot ou une voix de canard ?",
    "Si tu étais un ustensile de cuisine, lequel serais-tu ?",
    "Quelle est la question la plus stupide que tu aies cherchée sur Internet ?",
    "Si tu pouvais respirer sous l'eau ou voler, que choisirais-tu ?",
    "Plutôt vivre sans musique ou sans films ?",
    "Si tu devais être un méchant de Disney, qui serais-tu ?",
    "Quelle est la tradition humaine que les aliens trouveraient la plus bizarre ?",
    "Si tu pouvais agrandir une partie de ton corps de 50%, laquelle ?",
    "Plutôt avoir des cheveux qui changent de couleur selon ton humeur ou des yeux qui brillent dans le noir ?",
    "Si tu étais une boisson chaude, serais-tu café, thé ou chocolat ?",
    "Quel est le record du monde le plus stupide que tu pourrais battre ?",
    "Si tu pouvais lire un seul livre pour le reste de ta vie ?",
    "Plutôt être attaqué par 50 canards ou 1 ours ?",
    "Si tu devais créer une nouvelle fête nationale, on y célébrerait quoi ?",
    "Quel est l'objet que tu sauverais en premier dans un incendie (hors vivants) ?",
    "Si tu pouvais voir les statistiques au-dessus de la tête des gens, lesquelles voudrais-tu voir ?",
    "Plutôt avoir un bouton 'Rewind' ou un bouton 'Pause' dans ta vie ?",
    "Si tu étais une planète, comment t'appellerais-tu ?",
    "Quelle est la chose la plus bizarre que tu aies mangée au petit-déjeuner ?",
    "Si tu pouvais échanger ta voix avec un chanteur, qui serait-ce ?",
    "Plutôt être célèbre et détesté ou inconnu et adoré ?",
    "Si tu étais un fromage, lequel serais-tu ?",
    "Quelle est la loi de la physique que tu aimerais pouvoir enfreindre ?",
    "Si tu devais vivre dans une maison faite de bonbons ou de fromage ?",
    "Plutôt avoir un dragon ou une licorne ?",
    "Si tu étais un emoji, lequel utiliserais-tu le plus ?",
    "Quelle est la pire odeur que tu aies jamais sentie ?",
    "Si tu pouvais savoir la vérité sur un mystère non résolu, lequel choisirais-tu ?",
    "Plutôt ne plus jamais avoir de smartphone ou ne plus jamais avoir d'ordinateur ?"
  ],
  [Category.CHALLENGE]: [
    "Challenge : Regardez-vous dans les yeux pendant 60 secondes sans rire ni parler.",
    "Challenge : Faites-vous un massage des épaules de 3 minutes chacun.",
    "Challenge : Dansez un slow sur votre chanson préférée, là, tout de suite.",
    "Challenge : Dessine un portrait de l'autre en 2 minutes (même si tu ne sais pas dessiner).",
    "Challenge : Laissez votre téléphone dans une autre pièce pendant 1 heure.",
    "Challenge : Faites chacun une liste de 3 choses pour lesquelles vous êtes reconnaissants envers l'autre.",
    "Challenge : Cuisinez un plat ensemble en utilisant uniquement ce qu'il y a dans le frigo.",
    "Challenge : Recréez votre première photo de couple.",
    "Challenge : Écrivez chacun une lettre d'amour à lire dans 6 mois.",
    "Challenge : Organisez un pique-nique dans le salon.",
    "Challenge : Faites un concours de grimaces, le premier qui rit a perdu.",
    "Challenge : Chuchotez quelque chose de gentil à l'oreille de l'autre.",
    "Challenge : Planifiez votre prochain weekend en détails.",
    "Challenge : Donnez-vous un nouveau surnom mignon pour la journée.",
    "Challenge : Faites 10 squats ensemble en vous tenant la main.",
    "Challenge : Embrassez-vous comme si c'était la première fois.",
    "Challenge : Racontez-vous une blague, le premier qui rit masse les pieds de l'autre.",
    "Challenge : Faites un selfie le plus moche possible ensemble.",
    "Challenge : Mettez votre chanson préférée et chantez en playback avec passion.",
    "Challenge : Complimentez l'autre pendant 1 minute sans vous arrêter.",
    "Challenge : Nourrissez l'autre avec un aliment (chocolat, fruit) les yeux bandés.",
    "Challenge : Imitez l'autre, celui qui est imité doit deviner quelle habitude est visée.",
    "Challenge : Cherchez la constellation la plus proche ou regardez les nuages pendant 5 min.",
    "Challenge : Faites un pierre-feuille-ciseaux, le gagnant a droit à un baiser où il veut.",
    "Challenge : Échangez un vêtement (t-shirt, pull) pour la prochaine heure.",
    "Challenge : Racontez votre meilleur souvenir commun en un mot chacun, tour à tour.",
    "Challenge : Portez l'autre sur votre dos (ou essayez) pour faire un tour de la pièce.",
    "Challenge : Faites une bataille de pouces, le perdant fait la vaisselle/range.",
    "Challenge : Ne dites pas 'oui' ou 'non' pendant les 10 prochaines minutes.",
    "Challenge : Trouvez 5 objets rouges dans la pièce le plus vite possible."
  ],
  [Category.QUIZ]: [
    "Qui de nous deux est le plus susceptible de survivre sur une île déserte ?",
    "Qui de nous deux est le meilleur cuisinier ?",
    "Qui de nous deux a le plus mauvais caractère le matin ?",
    "Qui de nous deux dépense le plus d'argent inutilement ?",
    "Qui de nous deux est le plus romantique ?",
    "Qui de nous deux est le plus susceptible de pleurer devant un film ?",
    "Qui de nous deux a le meilleur sens de l'orientation ?",
    "Qui de nous deux est le plus bordélique ?",
    "Qui de nous deux ferait le meilleur président ?",
    "Qui de nous deux est le plus accro à son téléphone ?",
    "Qui de nous deux est le plus susceptible d'oublier un anniversaire ?",
    "Qui de nous deux est le plus drôle ?",
    "Qui de nous deux est le plus patient ?",
    "Qui de nous deux est le plus susceptible de faire une gaffe en public ?",
    "Qui de nous deux est le plus aventureux ?",
    "Qui de nous deux survivrait le plus longtemps dans un film d'horreur ?",
    "Qui de nous deux finirait en prison par accident ?",
    "Qui de nous deux deviendrait célèbre sur Internet pour une bêtise ?",
    "Qui de nous deux est le plus susceptible de rire à un enterrement ?",
    "Qui de nous deux oublierait de fermer la porte de la maison ?",
    "Qui de nous deux est le plus susceptible de parler à des animaux dans la rue ?",
    "Qui de nous deux chante le plus mal sous la douche ?",
    "Qui de nous deux est le plus susceptible de trébucher sur rien du tout ?",
    "Qui de nous deux prend le plus de temps pour se préparer le matin ?",
    "Qui de nous deux serait le premier à mourir dans une apocalypse zombie ?",
    "Qui de nous deux est le plus susceptible de manger le dernier biscuit sans demander ?",
    "Qui de nous deux est le plus susceptible d'adopter un animal errant sans prévenir ?",
    "Qui de nous deux est le plus susceptible de s'endormir au cinéma ?",
    "Qui de nous deux est le plus susceptible de gagner à un jeu de société ?",
    "Qui de nous deux est le plus susceptible de faire une scène pour une commande erronée ?",
    "Qui de nous deux est le plus susceptible de rejoindre un culte par accident ?",
    "Qui de nous deux est le plus susceptible de se faire tatouer sur un coup de tête ?",
    "Qui de nous deux est le plus susceptible de casser son téléphone ?",
    "Qui de nous deux commanderait le même plat au restaurant jusqu'à la fin de sa vie ?",
    "Qui de nous deux est le plus susceptible de se faire un ami dans les toilettes d'un bar ?",
    "Qui de nous deux est le plus susceptible d'oublier où la voiture est garée ?",
    "Qui de nous deux mangerait un yaourt périmé sans vérifier la date ?",
    "Qui de nous deux hurlerait le plus fort en voyant une araignée ?",
    "Qui de nous deux est le plus susceptible de bouder pour un détail ?",
    "Qui de nous deux est le plus susceptible d'organiser une surprise incroyable ?",
    "Qui de nous deux changerait de métier demain sur un coup de tête ?",
    "Qui de nous deux partirait vivre dans une cabane en forêt sans électricité ?",
    "Qui de nous deux gagnerait un concours de danse improvisé ?",
    "Qui de nous deux enverrait un SMS coquin à son patron par erreur ?",
    "Qui de nous deux rit de sa propre blague avant même de l'avoir finie ?",
    "Qui de nous deux est le plus susceptible de se cogner le petit orteil ?",
    "Qui de nous deux aura le plus d'abonnés sur Instagram plus tard ?",
    "Qui de nous deux est le plus susceptible d'écrire un livre sur sa vie ?",
    "Qui de nous deux ne se laverait pas pendant 3 jours en festival ?",
    "Qui de nous deux est le plus susceptible de tout plaquer pour faire le tour du monde ?",
    "Qui de nous deux serait en retard à son propre mariage ?",
    "Qui de nous deux tricherait au Monopoly sans remords ?",
    "Qui de nous deux pleure systématiquement en écoutant Adele ?",
    "Qui de nous deux ferait brûler de l'eau en cuisinant ?",
    "Qui de nous deux garderait un secret jusqu'à la tombe ?",
    "Qui de nous deux se déguiserait le mieux pour Halloween ?",
    "Qui de nous deux fait les pires jeux de mots ?",
    "Qui de nous deux a encore peur du noir secrètement ?",
    "Qui de nous deux ronfle le plus fort (ou parle en dormant) ?",
    "Qui de nous deux finirait le pot de Nutella à la petite cuillère en une fois ?",
    "Qui de nous deux est le plus susceptible d'avoir un enfant caché ?",
    "Qui de nous deux est le plus susceptible de devenir millionnaire par hasard ?",
    "Qui de nous deux pardonne le plus facilement ?",
    "Qui de nous deux est le plus susceptible de pleurer de joie pour un cadeau ?",
    "Qui de nous deux est le plus susceptible de perdre ses clés 5 fois par jour ?",
    "Qui de nous deux a le rire le plus contagieux ?",
    "Qui de nous deux ferait un meilleur espion ?",
    "Qui de nous deux crierait le plus fort dans des montagnes russes ?",
    "Qui de nous deux serait capable de manger le plus de piment ?",
    "Qui de nous deux pleurerait si on lui volait sa nourriture ?",
    "Qui de nous deux serait le premier à vouloir rentrer de soirée ?"
  ],
  [Category.YOU_RATHER]: [
    "Tu préfères ne plus jamais manger de fromage ou ne plus jamais manger de chocolat ?",
    "Tu préfères avoir le pouvoir de voler ou de devenir invisible ?",
    "Tu préfères vivre 100 ans dans le futur ou 100 ans dans le passé ?",
    "Tu préfères ne plus jamais pouvoir écouter de musique ou ne plus jamais pouvoir regarder de films ?",
    "Tu préfères avoir des bras en spaghetti ou des jambes en guimauve ?",
    "Tu préfères pouvoir parler à tous les animaux ou parler toutes les langues humaines ?",
    "Tu préfères être toujours en retard de 10 minutes ou toujours en avance de 20 minutes ?",
    "Tu préfères vivre sans internet pendant un an ou sans climatisation/chauffage pendant un an ?",
    "Tu préfères savoir comment tu vas mourir ou quand tu vas mourir ?",
    "Tu préfères avoir un bouton 'pause' dans ta vie ou un bouton 'retour en arrière' ?",
    "Tu préfères ne plus jamais pouvoir mentir ou devoir toujours dire tout ce que tu penses ?",
    "Tu préfères avoir des doigts à la place des orteils ou des orteils à la place des doigts ?",
    "Tu préfères être attaqué par 50 canards de la taille d'un cheval ou 1 cheval de la taille d'un canard ?",
    "Tu préfères vivre sur une île déserte seul(e) ou dans une ville bondée avec des gens que tu détestes ?",
    "Tu préfères ne plus jamais ressentir la douleur physique ou ne plus jamais ressentir la tristesse ?",
    "Tu préfères avoir le hoquet pour le reste de ta vie ou avoir toujours l'impression que tu vas éternuer sans y arriver ?",
    "Tu préfères être célèbre et détesté(e) ou inconnu(e) et adoré(e) ?",
    "Tu préfères perdre tous tes souvenirs ou ne plus jamais pouvoir en créer de nouveaux ?",
    "Tu préfères avoir une voix de robot ou une voix de canard ?",
    "Tu préfères manger une pizza à l'ananas tous les jours ou ne plus jamais manger de pizza ?",
    "Tu préfères trouver le véritable amour ou trouver une valise avec 10 millions d'euros ?",
    "Tu préfères pouvoir lire dans les pensées ou pouvoir te téléporter ?",
    "Tu préfères avoir toujours froid ou avoir toujours chaud ?",
    "Tu préfères vivre dans un monde de magie ou dans un monde de science-fiction très avancée ?",
    "Tu préfères avoir un dragon de compagnie ou une licorne de compagnie ?",
    "Tu préfères ne plus jamais pouvoir te laver les cheveux ou ne plus jamais pouvoir te brosser les dents ?",
    "Tu préfères être le/la meilleur(e) dans un domaine inutile ou être moyen(ne) dans tout ?",
    "Tu préfères vivre dans un film d'horreur ou dans une comédie romantique très clichée ?",
    "Tu préfères avoir des cheveux qui changent de couleur selon ton humeur ou des yeux qui brillent dans le noir ?",
    "Tu préfères ne plus jamais pouvoir utiliser de smartphone ou ne plus jamais pouvoir utiliser d'ordinateur ?"
  ],
  [Category.TRUE_FALSE]: [
    "Vrai ou Faux : Les hommes tombent amoureux plus vite que les femmes en moyenne.",
    "Vrai ou Faux : Les couples qui rient ensemble durent plus longtemps.",
    "Vrai ou Faux : Nous avons déjà eu un fou rire au pire moment possible.",
    "Vrai ou Faux : L'un de nous est un bien meilleur menteur que l'autre.",
    "Vrai ou Faux : Il est impossible d'éternuer les yeux ouverts.",
    "Vrai ou Faux : Les opposés s'attirent toujours en amour.",
    "Vrai ou Faux : Je connais ta commande préférée au restaurant par cœur.",
    "Vrai ou Faux : Les humains partagent 50% de leur ADN avec les bananes.",
    "Vrai ou Faux : L'un de nous a déjà secrètement jeté un vêtement moche de l'autre.",
    "Vrai ou Faux : La communication non-verbale représente plus de 50% de notre communication.",
    "Vrai ou Faux : Nous avons la même définition de ce qu'est une 'maison propre'.",
    "Vrai ou Faux : L'un de nous est beaucoup plus compétitif que l'autre aux jeux de société.",
    "Vrai ou Faux : Les éléphants sont les seuls animaux qui ne peuvent pas sauter.",
    "Vrai ou Faux : Je pourrais survivre une semaine entière sans mon téléphone.",
    "Vrai ou Faux : L'amour aveugle vraiment les gens face aux défauts de leur partenaire."
  ],
  [Category.STORYTELLER]: [
    "Imagine que nous nous réveillons demain avec la capacité de lire dans les pensées de l'autre. Que se passe-t-il pendant le petit-déjeuner ?",
    "Nous sommes en l'an 2150. Nous venons d'acheter notre première maison sur Mars. Décris notre première journée d'emménagement.",
    "Il était une fois, nous deux coincés dans un ascenseur avec un pingouin et une valise mystérieuse. Comment on s'en sort ?",
    "Imagine que notre vie de couple soit une série Netflix. Quel serait le titre de l'épisode d'aujourd'hui et quel en serait le résumé ?",
    "Nous trouvons une carte au trésor dans le grenier qui indique un endroit dans notre propre ville. Raconte le début de notre aventure.",
    "Imagine que nous avons le pouvoir de voyager dans le temps, mais seulement pour des durées de 5 minutes. Où allons-nous en premier ?",
    "Nous sommes les deux derniers survivants sur Terre, mais nous avons accès à tous les supermarchés. Quel est notre programme de la journée ?",
    "Imagine qu'un réalisateur veuille faire un film sur notre rencontre, mais dans le style d'un film d'action hollywoodien. Raconte la scène d'ouverture.",
    "Nous nous réveillons un matin et nous avons échangé nos corps. Quelle est la première chose que tu fais dans mon corps ?",
    "Imagine que nous adoptions un animal de compagnie magique. À quoi ressemble-t-il et quelle bêtise vient-il de faire dans le salon ?"
  ]
};

export const CATEGORY_COLORS: Record<Category, string> = {
  [Category.DEEP]: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  [Category.FUNNY]: 'bg-yellow-50 text-yellow-700 border-yellow-200',
  [Category.ROMANTIC]: 'bg-rose-50 text-rose-700 border-rose-200',
  [Category.FUTURE]: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  [Category.RANDOM]: 'bg-purple-50 text-purple-700 border-purple-200',
  [Category.CHALLENGE]: 'bg-orange-50 text-orange-700 border-orange-200',
  [Category.QUIZ]: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  [Category.YOU_RATHER]: 'bg-pink-50 text-pink-700 border-pink-200',
  [Category.TRUE_FALSE]: 'bg-teal-50 text-teal-700 border-teal-200',
  [Category.STORYTELLER]: 'bg-fuchsia-50 text-fuchsia-700 border-fuchsia-200',
};

export const CATEGORY_ICONS: Record<Category, string> = {
  [Category.DEEP]: '🧠',
  [Category.FUNNY]: '😂',
  [Category.ROMANTIC]: '❤️',
  [Category.FUTURE]: '🚀',
  [Category.RANDOM]: '🎲',
  [Category.CHALLENGE]: '🔥',
  [Category.QUIZ]: '❓',
  [Category.YOU_RATHER]: '⚖️',
  [Category.TRUE_FALSE]: '✅',
  [Category.STORYTELLER]: '📖',
};
